# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82a73f567336d6508f3663485937faa095276d997adaf491e8acc68dceabf1d5ac1f9e38e6bc1c6c971e0f7786de39265081d3ed1f3ede384ae70c73bae86e92
  gmaps_key: <%= ENV["MEDLOG_GMAPS"] %>
  encr_key: <%= ENV["ENCR_KEY"] %>

test:
  secret_key_base: 1bdc4ecac23cdbf50f3d2a75bc9ac2c5357129a9d84f31ae97ff950b391ce0a2bb86edfef814ae358e1d51fad9423e7814522331bda89b131372cce4be8b8799
  gmaps_key: <%= ENV["MEDLOG_GMAPS"] %>
  encr_key: <%= ENV["ENCR_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  gmaps_key: <%= ENV["GMAPS_KEY"] %>
  encr_key: <%= ENV["ENCR_KEY"] %>
